$primary = rgb(e4686e)
$surface = rgb(291415)
$secondary = rgb(e3a069)
$error = rgb(e3696f)
$tertiary = rgb(e3dd69)
$surface_lowest = rgb(150a0a)

general {
    col.active_border = $primary
    col.inactive_border = $surface
}

group {
    col.border_active = $secondary
    col.border_inactive = $surface
    col.border_locked_active = $error
    col.border_locked_inactive = $surface

    groupbar {
        col.active = $secondary
        col.inactive = $surface
        col.locked_active = $error
        col.locked_inactive = $surface
    }
}
