[general]

live_config_reload = true
import = ["~/.config/alacritty/themes/themes/hyper.toml"]


[window]
decorations = "None"
startup_mode = "Maximized"

[scrolling]
history = 20000
multiplier = 5

[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }
size = 11

[cursor]
style = { shape = "Beam", blinking = "On" }
blink_interval = 696
blink_timeout = 3
unfocused_hollow = false
thickness = 0.2

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
  # Open a new instance in cwd 
  { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" },
]
